# This file is generated by scripts/render-homebrew-formula.sh.
# Do not edit the url or sha256 by hand; regenerate it from a release tag instead.
class DevDomains < Formula
  desc "Friendly local domains for multiple dev servers using Caddy and lvh.me"
  homepage "https://github.com/gstark/dev-domains"
  url "https://github.com/gstark/dev-domains/archive/refs/tags/v0.1.5.tar.gz"
  sha256 "b7f45599b55dee1c0bb205d55bb512531a2340d5a63a2dcf83b42bf3f4c5fd26"
  license "MIT"

  depends_on "caddy"

  def install
    pkgshare.install "caddy", "docs", "scripts", "README.md", "LICENSE", "CONTRIBUTING.md", "CODE_OF_CONDUCT.md", "Makefile"
    inreplace "bin/dev-domains", "__DEV_DOMAINS_ROOT__", pkgshare.to_s
    bin.install "bin/dev-domains"
  end

  def caveats
    <<~EOS
      dev-domains installs caddy automatically via Homebrew dependencies.

      Important paths:
        ~/.config/dev-domains/Caddyfile
        ~/.config/dev-domains/apps
        /opt/homebrew/etc/Caddyfile
        #{opt_pkgshare}/docs

      First-time setup:
        dev-domains setup

      That command will:
        - create ~/.config/dev-domains with the root Caddy config
        - point the system Caddyfile at ~/.config/dev-domains/Caddyfile
        - start or restart caddy
        - use lvh.me hostnames like http://myapp.lvh.me

      No dnsmasq or /etc/resolver setup is required for lvh.me.
    EOS
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/dev-domains help")
  end
end
