#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/render-homebrew-formula.sh <tag> [output-path]

Examples:
  scripts/render-homebrew-formula.sh v0.1.0
  scripts/render-homebrew-formula.sh v0.1.0 Formula/dev-domains.rb
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 1 || $# -gt 2 ]]; then
  usage
  exit 1
fi

TAG="$1"
OUT="${2:-}"
REPO="${GITHUB_REPOSITORY:-gstark/dev-domains}"
URL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
TMP_FILE="$(mktemp /tmp/dev-domains-${TAG}.XXXXXX.tar.gz)"
trap 'rm -f "$TMP_FILE"' EXIT

curl -fsSL "$URL" -o "$TMP_FILE"
SHA256="$(shasum -a 256 "$TMP_FILE" | awk '{print $1}')"

VERSION="${TAG#v}"
FORMULA_CONTENT=$(cat <<EOF
# This file is generated by scripts/render-homebrew-formula.sh.
# Do not edit the url or sha256 by hand; regenerate it from a release tag instead.
class DevDomains < Formula
  desc "Friendly local domains for multiple dev servers using Caddy and lvh.me"
  homepage "https://github.com/gstark/dev-domains"
  url "${URL}"
  sha256 "${SHA256}"
  license "MIT"

  depends_on "caddy"

  def install
    pkgshare.install "caddy", "docs", "scripts", "README.md", "LICENSE", "CONTRIBUTING.md", "CODE_OF_CONDUCT.md", "Makefile"
    inreplace "bin/dev-domains", "__DEV_DOMAINS_ROOT__", pkgshare.to_s
    bin.install "bin/dev-domains"
  end

  def caveats
    <<~EOS
      dev-domains installs caddy automatically via Homebrew dependencies.

      Important paths:
        ~/.config/dev-domains/Caddyfile
        ~/.config/dev-domains/apps
        /opt/homebrew/etc/Caddyfile
        #{opt_pkgshare}/docs

      First-time setup:
        dev-domains setup

      That command will:
        - create ~/.config/dev-domains with the root Caddy config
        - point the system Caddyfile at ~/.config/dev-domains/Caddyfile
        - start or restart caddy
        - use lvh.me hostnames like http://myapp.lvh.me

      No dnsmasq or /etc/resolver setup is required for lvh.me.
    EOS
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/dev-domains help")
  end
end
EOF
)

if [[ -n "$OUT" ]]; then
  mkdir -p "$(dirname "$OUT")"
  printf '%s\n' "$FORMULA_CONTENT" > "$OUT"
  echo "Wrote $OUT for ${TAG} (${VERSION})"
else
  printf '%s\n' "$FORMULA_CONTENT"
fi

>&2 echo "Tarball URL: $URL"
>&2 echo "SHA256: $SHA256"
